# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BedSideMonitor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BedSideMonitor
    pod 'SwiftMQTT'
  target 'BedSideMonitorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BedSideMonitorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
